/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaLBFGS */

#ifndef _Included_JavaLBFGS
#define _Included_JavaLBFGS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaLBFGS
 * Method:    externalCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaLBFGS_externalCall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
